FROM ubuntu:latest
LABEL authors="baraklagziel"

ENTRYPOINT ["top", "-b"]

#FROM 313147870
#ARG JAR_VERSION
#USER ${USER}
#COPY target/auto-complete}.jar app.jar
#ENTRYPOINT ["java","-jar","/app.jar"]